/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajeroautomatico;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class RetirarDinero extends javax.swing.JFrame {

    /**
     * Creates new form RetirarDinero
     */
    ArrayList<UsuarioCajero> MenuUsuario = new ArrayList<>();
    int numusuario;

    public RetirarDinero(ArrayList<UsuarioCajero> MenuUsuario, int numusuario) {
        this.MenuUsuario = MenuUsuario;
        this.numusuario = numusuario;
        initComponents();
    }
    boolean retirar = false;
    boolean volver = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        btn_volverRetirardinero = new javax.swing.JButton();
        btn_aceptarRetiro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_Saldo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_CantRetirar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("RETIRAR DINERO");

        btn_volverRetirardinero.setBackground(new java.awt.Color(255, 255, 255));
        btn_volverRetirardinero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver_grande.jpg"))); // NOI18N
        btn_volverRetirardinero.setAlignmentY(2.0F);
        btn_volverRetirardinero.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_volverRetirardinero.setBorderPainted(false);
        btn_volverRetirardinero.setContentAreaFilled(false);
        btn_volverRetirardinero.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver_chico.jpg"))); // NOI18N
        btn_volverRetirardinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverRetirardineroActionPerformed(evt);
            }
        });

        btn_aceptarRetiro.setBackground(new java.awt.Color(255, 255, 255));
        btn_aceptarRetiro.setForeground(new java.awt.Color(0, 0, 0));
        btn_aceptarRetiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aceptar_s.jpg.png"))); // NOI18N
        btn_aceptarRetiro.setText("ACEPTAR");
        btn_aceptarRetiro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_aceptarRetiro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_aceptarRetiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_aceptarRetiro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aceptar_xl.jpg"))); // NOI18N
        btn_aceptarRetiro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_aceptarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarRetiroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Cantidad a Retirar:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Saldo:");

        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btn_volverRetirardinero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btn_aceptarRetiro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txt_Saldo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txt_CantRetirar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(177, 177, 177)
                        .addComponent(txt_Saldo))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btn_volverRetirardinero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_aceptarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(txt_CantRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(56, 56, 56)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_CantRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_aceptarRetiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_volverRetirardinero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarRetiroActionPerformed
        boolean bandera = false;
        retirar_dinero(bandera);

    }//GEN-LAST:event_btn_aceptarRetiroActionPerformed

    private void btn_volverRetirardineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverRetirardineroActionPerformed
        volver = true;
        Menu menu = new Menu(MenuUsuario, numusuario);
        menu.setVisible(volver);
        menu.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_btn_volverRetirardineroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetirarDinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetirarDinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetirarDinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetirarDinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptarRetiro;
    private javax.swing.JButton btn_volverRetirardinero;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField txt_CantRetirar;
    public static javax.swing.JTextField txt_Saldo;
    // End of variables declaration//GEN-END:variables

    public void retirar_dinero(boolean ban) {
        try {
            int valor_retirar = Integer.parseInt(txt_CantRetirar.getText());
            if (valor_retirar > MenuUsuario.get(numusuario).getDinero()) {
                JOptionPane.showMessageDialog(null, "el valor a retirar supera al saldo"
                        + "\n Intente con otro monto.");

            } else {

                MenuUsuario.get(numusuario).dinero = MenuUsuario.get(numusuario).dinero - valor_retirar;
                JOptionPane.showMessageDialog(null, "Dinero retirado"
                        + "\nSaldo disponible: " + MenuUsuario.get(numusuario).dinero);
                txt_CantRetirar.setText("");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ERROR al digitar importe a retirar: " + e);
            txt_CantRetirar.setText("");

        }
    }
}
